# Generated by Django 2.0.8 on 2019-01-15 22:51

import apps.theses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_create_theses_board_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesessystemsettings',
            options={'verbose_name': 'ustawienia systemu prac dyplomowych', 'verbose_name_plural': 'ustawienia systemu prac dyplomowych'},
        ),
        migrations.AlterField(
            model_name='thesessystemsettings',
            name='num_required_votes',
            field=models.SmallIntegerField(validators=[apps.theses.validators.validate_num_required_votes], verbose_name='Liczba głosów wymaganych do zaakceptowania'),
        ),
    ]
