# Generated by Django 2.0.8 on 2019-02-09 12:29

import apps.theses.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_create_theses_board_group'),
        ('users', '0011_create_external_contractors_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesessystemsettings',
            options={'verbose_name': 'ustawienia systemu prac dyplomowych', 'verbose_name_plural': 'ustawienia systemu prac dyplomowych'},
        ),
        migrations.AlterField(
            model_name='thesessystemsettings',
            name='num_required_votes',
            field=models.SmallIntegerField(validators=[apps.theses.validators.validate_num_required_votes], verbose_name='Liczba głosów wymaganych do zaakceptowania'),
        ),
        migrations.AddField(
            model_name='thesessystemsettings',
            name='rejecter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thesis',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='thesisvotebinding',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='thesisvotebinding',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Employee'),
        ),
    ]
